name: Deploy

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master

env:
  image: us-central1-docker.pkg.dev/rising-sector-360922/artifact-registry/gmail-watcher
  service-account: automation@rising-sector-360922.iam.gserviceaccount.com
  workload-identity-provider: projects/950322501036/locations/global/workloadIdentityPools/github-actions/providers/github-provider
  terraform-working-dir: ./terraform

jobs:
  terraform:
    runs-on: ubuntu-latest

    permissions:
      contents: 'write'
      id-token: 'write'
      pull-requests: 'write'

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Get changed files in the Python folder
        if: github.event_name == 'pull_request'
        id: changed-files-python
        uses: tj-actions/changed-files@v37
        with:
          files: python/**
          files_ignore: python/src/.pytest_cache/**

      - name: auth
        id: auth
        uses: google-github-actions/auth@v1
        with:
          workload_identity_provider: ${{ env.workload-identity-provider }}
          service_account: ${{ env.service-account }}

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v1.1.1

      - name: Login to Artifact Registry
        if: steps.changed-files-python.outputs.any_changed == 'true'
        run: |
          gcloud auth configure-docker us-central1-docker.pkg.dev --quiet

      - name: Docker build and push
        if: steps.changed-files-python.outputs.any_changed == 'true'
        run: |
          docker build -t ${{ env.image }}:${{ github.event.pull_request.head.sha }} -t ${{ env.image }}:latest .
          docker push ${{ env.image }}:${{ github.event.pull_request.head.sha }}
          docker push ${{ env.image }}:latest

      - name: Save image tag
        if: steps.changed-files-python.outputs.any_changed == 'true'
        run: |
          sed -i '/^image_tag/ s/.*/'"image_tag = \"${{ github.event.pull_request.head.sha }}\""'/' "./terraform/terraform.tfvars"

      - uses: stefanzweifel/git-auto-commit-action@v4
        if: steps.changed-files-python.outputs.any_changed == 'true'
        with:
          file_pattern: '*.tfvars'

      - name: Get changed files in the Terraform folder
        id: changed-files-terraform
        uses: tj-actions/changed-files@v37
        with:
          files: terraform/*.{tf,tfvars}
          files_ignore: terraform/.terraform/**

      - name: Configure Terraform
        if: steps.changed-files-terraform.outputs.any_changed == 'true'
        uses: hashicorp/setup-terraform@v2.0.3

      - name: Terraform Init
        if: steps.changed-files-terraform.outputs.any_changed == 'true'
        working-directory: ${{ env.terraform-working-dir }}
        run: terraform init

      - name: Terraform Fmt
        if: steps.changed-files-terraform.outputs.any_changed == 'true'
        working-directory: ${{ env.terraform-working-dir }}
        run: terraform fmt -recursive

      - name: Terraform Plan
        id: terraform-plan
        if: github.event_name == 'pull_request' && steps.changed-files-terraform.outputs.any_changed == 'true'
        working-directory: ${{ env.terraform-working-dir }}
        run: terraform plan -no-color

      - name: Terraform Apply
        if: github.event_name == 'push' && steps.changed-files-terraform.outputs.any_changed == 'true'
        working-directory: ${{ env.terraform-working-dir }}
        run: terraform apply --auto-approve

      - uses: actions/github-script@v6
        if: github.event_name == 'pull_request'
        env:
          PLAN: "terraform\n${{ steps.terraform-plan.outputs.stdout }}"
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            // 1. Retrieve existing bot comments for the PR
            const { data: comments } = await github.rest.issues.listComments({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number,
            })
            const botComment = comments.find(comment => {
              return comment.user.type === 'Bot' && comment.body.includes('Terraform Plan')
            })

            // 2. Prepare format of the comment
            const output = `
            #### Terraform Plan ðŸ“–\`${{ steps.terraform-plan.outcome }}\`

            <details><summary>Show Plan</summary>

            \`\`\`\n
            ${process.env.PLAN}
            \`\`\`

            </details>

            *Pusher: @${{ github.actor }}, Action: \`${{ github.event_name }}\`, Working Directory: \`${{ env.terraform-working-dir }}\`, Workflow: \`${{ github.workflow }}\`*`;

            // 3. If we have a comment, update it, otherwise create a new one
            if (botComment) {
              github.rest.issues.updateComment({
                owner: context.repo.owner,
                repo: context.repo.repo,
                comment_id: botComment.id,
                body: output
              })
            } else {
              github.rest.issues.createComment({
                issue_number: context.issue.number,
                owner: context.repo.owner,
                repo: context.repo.repo,
                body: output
              })
            }